package e

var MsgFlags = map[ErrCode]string{
	SUCCESS:        "请求成功",
	INVALID_PARAMS: "请求参数错误",
	ERROR:          "请求失败",

	ERROR_AUTH_CHECK_TOKEN_FAIL:                   "Token鉴权失败", //权限验证错误
	ERROR_AUTH_CHECK_TOKEN_TIMEOUT:                "Token已超时",
	ERROR_AUTH_TOKEN:                              "Token生成失败",
	ERROR_AUTH:                                    "用户权限错误",
	ERROR_PASSWD:                                  "密码错误",
	ERROR_AUTH_USER_AUTHENTICATED:                 "用户已认证",
	ERROR_AUTH_USER_NOT_AUTHENTICATED:             "用户未认证",
	ERROR_AUTH_USER_NOT_FOUND:                     "账户或密码错误，请重新输入",
	ERROR_AUTH_USER_NOT_LOGIN:                     "用户未登录",
	ERROR_AUTH_USER_NO_USERID:                     "未获取到用户id",
	ERROR_AUTH_USER_NO_DEPARTMENTID:               "未获取到所属部门id",
	ERROR_AUTH_USER_NO_LEVEL:                      "未获取到访问权限级别",
	ERROR_CHAIN_FOBRID_NO_AUTH:                    "没有该链访问权限", //链操作权限
	ERROR_ORG_FOBRID_NO_AUTH:                      "没有该组织访问权限",
	ERROR_PEER_FOBRID_NO_AUTH:                     "没有该节点访问权限",
	ERROR_CHAIN_FOBRID_STOP_ORG_PEER:              "网络初始化组织和节点禁止单独停止",
	ERROR_CHAIN_FOBRID_LEAVE_NETWORK:              "网络初始化组织和节点禁止单独退出网络",
	ERROR_CHAIN_FOBRID_ACTION_PEER:                "当前操作将导致节点所在网络无法正常运行",
	ERROR_CHAIN_FOBRID_CEATE_DEPARTMENT_PEER_AURH: "无创建该部门节点权限",
	ERROR_DB_INSERT_FAIL:                          "数据写入错误", //数据库错误
	ERROR_DB_GET_FAIL:                             "数据获取错误",
	ERROR_DB_UPDATE_FAIL:                          "数据更新错误",
	ERROR_DB_DELETE_FAIL:                          "数据删除错误",
	ERROR_DB_ROWS_NO_EFFACT:                       "数据未更新",
	ERROR_DB_GET_COUNT_FAIL:                       "数据统计总数错误",
	ERROR_DB_CREATE_TABLE:                         "创建数据表错误",
	ERROR_DB_SESSION_BEGIN_FAIL:                   "数据事务开始错误",
	ERROR_DB_SESSION_ACTION_FAIL:                  "数据事务处理错误",
	ERROR_DB_SESSION_COMMIT_FAIL:                  "数据事务提交错误",
	ERROR_DB_SESSION_ROLLBACK_FAIL:                "数据事务回滚错误",
	ERROR_UPLOAD_SAVE_FILE_FAIL:                   "上传文件失败", //文件上传错误
	ERROR_UPLOAD_CHECK_FILE_FAIL:                  "上传文件检查失败",
	ERROR_UPLOAD_CHECK_FILE_FORMAT:                "校验文件错误，文件格式或大小有问题",
	ERROR_READ_FILE_FAIL:                          "读取文件失败",
	ERROR_JSON_MARSHAL:                            "获取数据序类化错误", //数据序列化错误
	ERROR_JSON_UNMARSHAL:                          "数据反序列化错误",
	ERROR_K8S_RESOURCES_CPU_NOT_ENOUGH:            "服务器CPU资源不足", //k8s资源
	ERROR_K8S_RESOURCES_MEM_NOT_ENOUGH:            "服务器内存资源不足",
	ERROR_K8S_RESOURCES_DISK_NOT_ENOUGH:           "服务器硬盘资源不足",
	ERROR_K8S_RESOURCES_NOT_ENOUGH:                "服务器资源不足，请扩充资源后重新尝试！",
	ERROR_ACCOUNT_CREATE_FAIL:                     "账户创建失败", //账户创建错误
	ERROR_ACCOUNT_DECODE_FAIL:                     "账户密文解密失败",
	ERROR_ACCOUNT_ENCODE_FAIL:                     "账户密文加密失败",
	ERROR_ACCOUNT_CHECK_FAIL:                      "账户安全码校验失败",
	ERROR_COMMON_PALTFORM_REQUEST_FAIL:            "公共平台访问错误", //平台错误
	ERROR_COMMON_PALTFORM_DEPARTMENT_GET_FAIL:     "公共平台获取部门列表错误",
	ERROR_CROSS_PALTFORM_REQUEST_FAIL:             "跨平台模块访问错误",
	ERROR_CROSS_PALTFORM_RECEIVE_DATA:             "消息平台传入数据格式错误",
	ERROR_SIPC_ENGINE_REQUEST_TYPE_FAIL:           "sipc 引擎返回格式错误", //sipc chain error
	ERROR_SIPC_ENGINE_REQUEST_FAIL:                "Sipc 引擎请求失败",
	ERROR_SIPC_BUILD_CHAIN_FAIL:                   "区块链构建失败",
	ERROR_SIPC_BUILD_PEER_FAIL:                    "节点构建失败",
	ERROR_SIPC_RUN_CHAIN_FAIL:                     "区块链运行失败",
	ERROR_SIPC_RUN_PEER_FAIL:                      "节点运行失败",
	ERROR_SIPC_STOP_CHAIN_FAIL:                    "区块链停止失败",
	ERROR_SIPC_STOP_PEER_FAIL:                     "节点停止失败",
	ERROR_SIPC_RELEASE_CHAIN_FAIL:                 "区块链资源释放失败",
	ERROR_SIPC_RELEASE_PEER_FAIL:                  "节点资源释放失败",
	ERROR_SIPC_RELEASE_NODE_INFO:                  "获取服务器信息失败",
	ERROR_SIPC_RELEASE_NODE_RESOURCES:             "获取服务器资源详情失败",
	ERROR_SIPC_RELEASE_NODE_AVAILABLE_RESOURCES:   "获取服务器可用空间资源失败",
	ERROR_SIPC_GET_BLOCK_NUMBER_FAIL:              "获取区块高度失败", //manger
	ERROR_SIPC_GET_LASTEST_BLOCKS_FAIL:            "获取最新区块数据失败",
	ERROR_SIPC_GET_BLOCK_FAIL:                     "获取指定区块失败",
	ERROR_SIPC_GET_TRANSACTION_FAIL:               "获取指定交易失败",
	ERROR_SIPC_GET_PODS_FAIL:                      "获取pods信息失败",
	ERROR_SIPC_GET_RESOUCES_FAIL:                  "获取节点资源失败",
	ERROR_SIPC_START_MINER_FAIL:                   "启动挖矿失败",
	ERROR_SIPC_SEND_TRANSACTION_FAIL:              "发送交易失败",
	ERROR_SIPC_JION_NETWORK_FAIL:                  "节点加入网络错误",
	ERROR_SIPC_LEAVE_NETWORK_FAIL:                 "节点退出网络错误",
	ERROR_SIPC_UPGRADE_ROLE_FAIL:                  "节点升级角色错误",
	ERROR_SIPC_DOWNGRADE_ROLE_FAIL:                "节点降级角色错误",
	ERROR_SIPC_ADD_ADMIN_PEER_FAIL:                "添加管理员节点错误",
	ERROR_SIPC_INIT_ADMIN_FAIL:                    "初始化管理员错误",
	ERROR_SIPC_ADD_NEW_SIPE_INIT_FAIL:             "新加入节点初始化错误",
	ERROR_SIPC_INTER_CONNECT_PEER_FAIL:            "节点内部连接错误",
	ERROR_SIPC_PEER_RESOURCES_CHANGE_FAIL:         "节点资源修改失败",
	ERROR_SIPC_LEDGER_QUERY_FAIL:                  "未查询到该条数据信息",
	ERROR_SIPC_CONTRACT_DEPLOY_FAIL:               "合约安装错误", //contract
	ERROR_SIPC_CONTRACT_INVOKE_FAIL:               "合约调用错误",
	ERROR_SIPC_CHAIN_NOT_BUILD:                    "区块链未构建", //SIPC网络状态异常
	ERROR_SIPC_PEER_NOT_BUILD:                     "节点未构建",
	ERROR_SIPC_CHAIN_NOT_RUN:                      "区块链未运行",
	ERROR_SIPC_PEER_NOT_RUN:                       "节点未运行",
	ERROR_SIPC_CHAIN_STATUS_FORBID:                "该链当前状态无法执行该操作",
	ERROR_SIPC_PEER_STATUS_FORBID:                 "该节点当前状态无法执行该操作",
	ERROR_SIPC_CHAIN_PEER_NOT_ALL_STOP:            "该链当前节点未完全停止，请稍等",
	ERROR_SIPC_CHAIN_PEER_NOT_STOP:                "该节当前未停止，请稍后再试",
	ERROR_SIPC_CHAIN_USER_ALREADY_EXIST:           "该用户已被邀请加入该链中，不能重复加入",
	ERROR_SIPC_CHAIN_TASK_NOT_DONE:                "该链当前任务未处理完毕，请稍后尝试",
	ERROR_SIPC_CHAIN_NOT_EXIST:                    "区块链不存在", //SIPC访问资源不存在
	ERROR_SIPC_PEER_NOT_EXIST:                     "节点不存在",
	ERROR_SIPC_CONTRACT_NOT_EXIST:                 "合约不存在",
	ERROR_SIPC_ACCOUNT_NOT_EXIST:                  "账户不存在",

	ERROR_HTO_MODULE_USERS_FAIL:                   "获取指定模块的用户列表失败",
	ERROR_HTO_NOTICE_SUBMIT_FAIL:                  "系统日志提交失败",


	ERROR_CREATE_CHANNEL_FAILED:                   "创建通道失败",
	ERROR_JOIN_CHANNEL_FAILED:                     "加入通道失败",
	ERROR_INSTALL_CHAINCODE_FAILED:                "安装链码失败",
	ERROR_PACKAGE_CHAINCODE_FAILED:                "打包链码失败",
	ERROR_APPROVE_CHAINCODE_FAILED:                "批准链码失败",
	ERROR_COMMIT_CHAINCODE_FAILED:                 "提交链码失败",
	ERROR_INVOKE_CHAINCODE_FAILED:                 "调用链码失败",
	ERROR_QUERY_CHAINCODE_FAILED:                  "查询链码失败",
	ERROR_INIT_CHAINCODE_FAILED:                   "初始化链码失败",
	ERROR_QUERY_LEDGER_FAILED:                     "查询账本失败",
	ERROR_QUERY_BLOCKNUM_FAILED:                   "查询块高",
	ERROR_QUERY_CONFIG_FAILED:                     "查询配置块失败",
	ERROR_QUERY_BLOCK_BY_BLOCKNUM_FAILED:          "通过块高查询块失败",
	ERROR_QUERY_BLOCK_BY_BLOCKHASH_FAILED:         "通过块hash查询块失败",
	ERROR_QUERY_BLOCK_BY_TXID_FAILED:              "通过交易id查询块失败",
	ERROR_QUERY_TX_BY_HASH_FAILED:                 "通过交易hash查询交易失败",
	ERROR_UPGRADE_CHAINCODE_FAILED:                "升级链码失败",
	ERROR_TYPE_CHANGE_FAILED:                      "类型转换失败",

}